"""Compile- AND lint-check every code card's Rust against your local toolchain.

For each `solution:` (code cards) and each concept `code:` snippet, this wraps
the code in its own module/function inside one generated crate and runs
`cargo clippy` with `-D warnings`. That fails on compile errors, ordinary
warnings (unused vars/imports, needless mut, ...), AND clippy's idiomatic lints
(needless borrows like |&&x|, redundant clone/copied, manual loops, unnecessary
fold, ...). Dead-code from the wrapping is suppressed on purpose.

Requires a local Rust toolchain. Run from the repo root:

    python check_cards.py                 # all cards/*.yaml
    python check_cards.py cards/match.yaml # just one file
    python check_cards.py --build          # plain `cargo build` (skip clippy)

Each block lives in a module `sol_<topic>_<n>` / `ex_<topic>_<n>` with a comment
naming the card, so failures are easy to trace back.
"""
import glob
import os
import re
import shutil
import subprocess
import sys
import textwrap

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
CHECK = os.path.join(HERE, "_check")


def read(p):
    with open(p, "r", encoding="utf-8") as f:
        return f.read()


def first_line(s):
    for ln in (s or "").splitlines():
        if ln.strip():
            return ln.strip()
    return ""


def indent(s, n=4):
    return textwrap.indent(s.rstrip("\n"), " " * n)


def collect(paths):
    items = []
    for p in paths:
        stem = os.path.splitext(os.path.basename(p))[0]
        ident = re.sub(r"[^a-z0-9_]", "_", stem.lower())
        for i, c in enumerate(yaml.safe_load(read(p)) or []):
            if c.get("type", "code") == "concept":
                code = c.get("code")
                if not code:
                    continue
                name = f"ex_{ident}_{i}"
                comment = f"// [{stem} #{i} concept] {first_line(c.get('question',''))}"
                body = (f"mod {name} {{\n    #![allow(dead_code)]\n"
                        f"    fn demo() {{\n{indent(code, 8)}\n    }}\n}}")
                items.append((name, comment, body))
            else:
                sol = c.get("solution")
                if not sol:
                    continue
                name = f"sol_{ident}_{i}"
                comment = f"// [{stem} #{i}] {first_line(c.get('instruction',''))}"
                body = (f"mod {name} {{\n    #![allow(dead_code)]\n"
                        f"{indent(sol, 4)}\n}}")
                items.append((name, comment, body))
    return items


def write_crate(items):
    if os.path.isdir(CHECK):
        shutil.rmtree(CHECK)
    os.makedirs(os.path.join(CHECK, "src"))
    with open(os.path.join(CHECK, "Cargo.toml"), "w", encoding="utf-8") as f:
        f.write("[package]\nname = \"card_check\"\nversion = \"0.0.0\"\n"
                "edition = \"2021\"\n\n[lib]\npath = \"src/lib.rs\"\n")
    parts = ["// AUTO-GENERATED by check_cards.py — do not edit.\n"]
    for name, comment, body in items:
        parts += [comment, body, ""]
    with open(os.path.join(CHECK, "src", "lib.rs"), "w", encoding="utf-8") as f:
        f.write("\n".join(parts))


def have(cmd):
    try:
        subprocess.run(cmd, cwd=CHECK, capture_output=True)
        return True
    except FileNotFoundError:
        return False


def main():
    argv = [a for a in sys.argv[1:] if a != "--build"]
    use_build = "--build" in sys.argv
    paths = ([os.path.join(HERE, a) for a in argv] if argv
             else sorted(glob.glob(os.path.join(HERE, "cards", "*.yaml"))))
    items = collect(paths)
    write_crate(items)
    print(f"Generated {len(items)} checkable blocks in {CHECK}/src/lib.rs")

    if not shutil.which("cargo"):
        print("\n[!] No `cargo` on PATH. Install Rust (https://rustup.rs) and "
              "re-run; the crate is ready to inspect/build manually.")
        return 2

    env = dict(os.environ, RUSTFLAGS="-D warnings")
    clippy_ok = (not use_build) and have(["cargo", "clippy", "--version"])
    if clippy_ok:
        print("Running: cargo clippy -- -D warnings ...\n")
        r = subprocess.run(["cargo", "clippy", "--quiet", "--", "-D", "warnings"],
                           cwd=CHECK, env=env)
        tool = "clippy (compile + idiomatic lints)"
    else:
        if not use_build:
            print("[!] clippy not found (`rustup component add clippy`); "
                  "falling back to plain build.\n")
        print("Running: cargo build -D warnings ...\n")
        r = subprocess.run(["cargo", "build", "--quiet"], cwd=CHECK, env=env)
        tool = "build (compile only)"

    if r.returncode == 0:
        print(f"\n✓ All {len(items)} blocks pass {tool} with zero warnings.")
    else:
        print(f"\n✗ {tool} reported problems above. Each block is module "
              "sol_<topic>_<n> / ex_<topic>_<n>; the comment above it names the card.")
    return r.returncode


if __name__ == "__main__":
    sys.exit(main())
