"""Compile-, lint- AND test-check every code card's Rust against your toolchain.

For each `solution:` (code cards) and each concept `code:` snippet, this wraps
the code in its own module inside one generated crate, then:

  1. `cargo clippy -- -D warnings`  — compile errors + ordinary warnings +
     clippy's idiomatic lints (needless borrows, redundant clones, etc.).
  2. `cargo test`                   — runs each card's `tests:` block (assert
     statements), proving the solution is actually CORRECT, not just compiling.

Dead-code from the wrapping is suppressed on purpose.

Requires a local Rust toolchain (`rustup component add clippy`). From repo root:

    python check_cards.py                          # all cards/*.yaml
    python check_cards.py cards/neetcode__arrays_hashing.yaml
    python check_cards.py --build                  # skip clippy (compile+test only)

A card adds tests like:

    tests: |
      assert_eq!(two_sum(&[2, 7, 11, 15], 9), Some((0, 1)));
      assert_eq!(two_sum(&[3, 2, 4], 6), Some((1, 2)));

The asserts run inside the solution's module, so they can call its functions
directly. Each block is module `sol_<topic>_<n>` / `ex_<topic>_<n>`, with a
comment naming the card, so failures are easy to trace back.
"""
import glob
import os
import re
import shutil
import subprocess
import sys
import textwrap

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
CHECK = os.path.join(HERE, "_check")


def read(p):
    with open(p, "r", encoding="utf-8") as f:
        return f.read()


def first_line(s):
    for ln in (s or "").splitlines():
        if ln.strip():
            return ln.strip()
    return ""


def indent(s, n=4):
    return textwrap.indent(s.rstrip("\n"), " " * n)


def collect(paths):
    items = []
    for p in paths:
        stem = os.path.splitext(os.path.basename(p))[0]
        ident = re.sub(r"_+", "_", re.sub(r"[^a-z0-9_]", "_", stem.lower())).strip("_")
        for i, c in enumerate(yaml.safe_load(read(p)) or []):
            if c.get("type", "code") == "concept":
                code = c.get("code")
                if not code:
                    continue
                name = f"ex_{ident}_{i}"
                comment = f"// [{stem} #{i} concept] {first_line(c.get('question',''))}"
                body = (f"mod {name} {{\n    #![allow(dead_code)]\n"
                        f"    fn demo() {{\n{indent(code, 8)}\n    }}\n}}")
                items.append((name, comment, body))
            else:
                sol = c.get("solution")
                if not sol:
                    continue
                name = f"sol_{ident}_{i}"
                comment = f"// [{stem} #{i}] {first_line(c.get('instruction',''))}"
                lines = [f"mod {name} {{", "    #![allow(dead_code)]", indent(sol, 4)]
                tests = c.get("tests")
                if tests:
                    # cfg(test) so clippy (a non-test build) won't lint asserts,
                    # while `cargo test` still compiles and runs them.
                    lines += ["", "    #[cfg(test)]", "    mod tests {",
                              "        use super::*;", "        #[test]",
                              "        fn card_test() {", indent(tests, 12),
                              "        }", "    }"]
                lines.append("}")
                items.append((name, comment, "\n".join(lines)))
    return items


def write_crate(items):
    if os.path.isdir(CHECK):
        shutil.rmtree(CHECK)
    os.makedirs(os.path.join(CHECK, "src"))
    with open(os.path.join(CHECK, "Cargo.toml"), "w", encoding="utf-8") as f:
        f.write("[package]\nname = \"card_check\"\nversion = \"0.0.0\"\n"
                "edition = \"2021\"\n\n[lib]\npath = \"src/lib.rs\"\n")
    parts = ["// AUTO-GENERATED by check_cards.py — do not edit.\n"]
    for _name, comment, body in items:
        parts += [comment, body, ""]
    with open(os.path.join(CHECK, "src", "lib.rs"), "w", encoding="utf-8") as f:
        f.write("\n".join(parts))


def have(cmd):
    try:
        subprocess.run(cmd, cwd=CHECK, capture_output=True)
        return True
    except FileNotFoundError:
        return False


def main():
    argv = [a for a in sys.argv[1:] if a != "--build"]
    skip_clippy = "--build" in sys.argv
    paths = ([os.path.join(HERE, a) for a in argv] if argv
             else sorted(glob.glob(os.path.join(HERE, "cards", "*.yaml"))))
    items = collect(paths)
    write_crate(items)
    print(f"Generated {len(items)} checkable blocks in {CHECK}/src/lib.rs")

    if not shutil.which("cargo"):
        print("\n[!] No `cargo` on PATH. Install Rust (https://rustup.rs) and "
              "re-run; the crate is ready to inspect/build manually.")
        return 2

    env = dict(os.environ, RUSTFLAGS="-D warnings")
    rc = 0

    if not skip_clippy and have(["cargo", "clippy", "--version"]):
        print("\n=> cargo clippy -- -D warnings\n")
        rc |= subprocess.run(
            ["cargo", "clippy", "--quiet", "--", "-D", "warnings"],
            cwd=CHECK, env=env).returncode
    elif not skip_clippy:
        print("[!] clippy not found (`rustup component add clippy`); skipping lints.")

    print("\n=> cargo test\n")
    rc |= subprocess.run(["cargo", "test", "--quiet"], cwd=CHECK, env=env).returncode

    if rc == 0:
        print(f"\n✓ All {len(items)} blocks compile, lint clean, and pass their tests.")
    else:
        print("\n✗ Problems above. Each block is module sol_<topic>_<n> / "
              "ex_<topic>_<n>; the comment above it names the card.")
    return rc


if __name__ == "__main__":
    sys.exit(main())
